// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu-mQ0LTHfep0Hl17MNJ8YfYrTZhHipOQ',
    appId: '1:309246116680:web:7144a7463f32c66f89697d',
    messagingSenderId: '309246116680',
    projectId: 'seraphic-amp-459917-p5',
    authDomain: 'seraphic-amp-459917-p5.firebaseapp.com',
    storageBucket: 'seraphic-amp-459917-p5.firebasestorage.app',
    measurementId: 'G-QQKMB85B0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZwuA3KwlOeREllCj8Z4RpR7TqWZL9kY',
    appId: '1:309246116680:android:6524b4953e1fb87489697d',
    messagingSenderId: '309246116680',
    projectId: 'seraphic-amp-459917-p5',
    storageBucket: 'seraphic-amp-459917-p5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFSaNFhKEBgdqOiGIF3koLWaIPrlAE1RQ',
    appId: '1:309246116680:ios:13d3a63bd1a1397c89697d',
    messagingSenderId: '309246116680',
    projectId: 'seraphic-amp-459917-p5',
    storageBucket: 'seraphic-amp-459917-p5.firebasestorage.app',
    iosBundleId: 'com.example.securepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFSaNFhKEBgdqOiGIF3koLWaIPrlAE1RQ',
    appId: '1:309246116680:ios:13d3a63bd1a1397c89697d',
    messagingSenderId: '309246116680',
    projectId: 'seraphic-amp-459917-p5',
    storageBucket: 'seraphic-amp-459917-p5.firebasestorage.app',
    iosBundleId: 'com.example.securepay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu-mQ0LTHfep0Hl17MNJ8YfYrTZhHipOQ',
    appId: '1:309246116680:web:c2f86ead7d44d65489697d',
    messagingSenderId: '309246116680',
    projectId: 'seraphic-amp-459917-p5',
    authDomain: 'seraphic-amp-459917-p5.firebaseapp.com',
    storageBucket: 'seraphic-amp-459917-p5.firebasestorage.app',
    measurementId: 'G-RCMBLV4JZT',
  );
}